# Generated by Django 4.2.10 on 2024-03-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='club_notice',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
