# Generated by Django 4.2.10 on 2024-03-05 18:07

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_bleach.models.BleachField(),
        ),
    ]
