# Generated by Django 4.2.10 on 2024-03-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Metadata Categories',
                'db_table': 'products_metadata_categories',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='care_instructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key_features',
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.metadatacategories')),
                ('products', models.ManyToManyField(blank=True, related_name='Metadata', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'metadata',
            },
        ),
    ]
