# Generated by Django 4.2.10 on 2024-03-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_metadatacategories_remove_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatacategories',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='Metadata', to='products.product', verbose_name='Select A Product'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value',
            field=models.TextField(verbose_name='Input Product Information'),
        ),
    ]
