# Generated by Django 4.2.10 on 2024-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_metadatacategories_friendly_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='Metadata', to='products.product'),
        ),
    ]
