# Generated by Django 4.2.10 on 2024-03-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_metadata_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
