# Generated by Django 4.2.10 on 2024-04-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.metadatacategories'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Input Product Information'),
        ),
    ]
