# Generated by Django 4.2.10 on 2024-04-01 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_metadata_category_alter_metadata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.metadatacategories'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='value',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Input Product Information'),
            preserve_default=False,
        ),
    ]
